// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPUjZjtuRsF6HmlJgiRsGy1F5Qm4V_LuY',
    appId: '1:999044995410:web:839477a7f1876ae1dec28b',
    messagingSenderId: '999044995410',
    projectId: 'tasklist-c103e',
    authDomain: 'tasklist-c103e.firebaseapp.com',
    storageBucket: 'tasklist-c103e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5T30CLlzgTnThzcMJY5c6KpUvXxOAzM',
    appId: '1:999044995410:android:145daf2fc7e8b281dec28b',
    messagingSenderId: '999044995410',
    projectId: 'tasklist-c103e',
    storageBucket: 'tasklist-c103e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGzVeDG3eUhecmV3pMT0DROtGP0m9nVas',
    appId: '1:999044995410:ios:552cd15552f8fb62dec28b',
    messagingSenderId: '999044995410',
    projectId: 'tasklist-c103e',
    storageBucket: 'tasklist-c103e.appspot.com',
    iosClientId: '999044995410-hv4v3at0shm3nj55i8ndr39ni73hjudb.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGzVeDG3eUhecmV3pMT0DROtGP0m9nVas',
    appId: '1:999044995410:ios:552cd15552f8fb62dec28b',
    messagingSenderId: '999044995410',
    projectId: 'tasklist-c103e',
    storageBucket: 'tasklist-c103e.appspot.com',
    iosClientId: '999044995410-hv4v3at0shm3nj55i8ndr39ni73hjudb.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
